name = "AdaptiveDesignOptimization"
uuid = "5f210a59-4c6a-4c2f-87d5-5cd98d51789a"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distributions = "v0.24.13"
Parameters = "v0.12.2"
SafeTestsets = "v0.0.1"
StatsFuns = "v0.9.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
